name: java-maven-build
description: Used for building Java Applications
inputs:
  package-options:
    required: true
    description: Build, Test and Package
  java-version:
    required: true
    type: string
    description: Java Version

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{inputs.java-version}}
        distribution: 'temurin'
        cache: maven
    - name: Run Package Options
      if: ${{inputs.package-options != ''}}
      shell: bash
      run: |
        echo 'Run Package Options'
        mvn ${{inputs.package-options}}    
    
