name: java-sonar-analysis
description: Java Sonar Analysis
inputs:
  sonar-token:
    required: true
    type: string
    description: Sonar Token
  sonar-options:
    required: false
    type: string
    default: 'sonar:sonar -Dsonar.projectKey=karlcubilo -Dsonar.organization=karlcubilo -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{inputs.sonar-token}} -Dsonar.scm.disabled=true'
    description: Sonar Command

runs:
  using: composite

  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Run Sonar Analysis
    shell: bash
    run: |
      echo 'Run Sonar Analysis'
      mvn ${{inputs.sonar-options}}
