name: java-sonar-analysis
description: Java Sonar Analysis
inputs:
  sonar-options:
    required: false
    type: string
    description: Sonar Command
  java-version:
    required: true
    type: string
    description: Java Version

runs:
  using: composite

  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up JDK
    uses: actions/setup-java@v3
    with:
      java-version: ${{inputs.java-version}}
      distribution: 'temurin'
      cache: maven  
  - name: Run Sonar Analysis
    shell: bash
    run: |
      echo 'Run Sonar Analysis'
      mvn ${{inputs.sonar-options}}
