name: Java CI Workflow
on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
        description: Application Name
      build-options:
        required: false
        type: string
        default: clean verify -Dci.buildNumber=lb-${{github.ref_name}}-${{github.sha}}-${{github.run_number}} -Dci.buildURL=${{github.repositoryUrl}}
        description: Build and Test
      package-options:
        required: false
        type: string
        description: Build, Test and Package
      run-sonar:
        required: false
        type: string
        description: Run Sonar Analysis
      java-version:
        required: true
        type: string
        description: Java Version
     
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps: 
    -  name: Maven Build
       uses: karlcubilo/lb-gitops-actions/java-maven-build@latest
       with:
         package-options: ${{inputs.package-options}}
         java-version: ${{inputs.java-version}}
  sonar-analysis: 
    if: ${{inputs.run-sonar}} == 'true'
    runs-on: ubuntu-latest
    steps:
    -  name: Sonar Analysis
       uses: karlcubilo/lb-gitops-actions/java-sonar-analysis@latest
       with:
         sonar-options: ${{inputs.sonar-options}}
     
