name: Java CI Workflow

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
        description: Application Name
      build-options:
        required: true
        type: string
        default: clean verify -Dci.buildNumber=lb-${{github.ref_name}}-${{github.sha}}-${{github.run_number}} -Dci.buildURL=${{github.repositoryUrl}}
        description: Build and Test
      package-options:
        required: false
        type: string
        description: Build, Test and Package
      run-sonar:
        required: false
        type: string
        description: Run Sonar Analysis
      sonar-options:
        required: false
        type: string
        default: 'sonar:sonar -Dsonar.projectKey=karlcubilo -Dsonar.organization=karlcubilo -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{secrets.SONAR_TOKEN}} -Dsonar.scm.disabled=true'
        description: Sonar Parameters



jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps: 
    -  name: Maven Build
       uses: 
       with:
         package-options: ${{inputs.package-options}}
  sonar-analysis: 
    runs-on: ubuntu-latest
    steps:
    -  name: Sonar Analysis
       uses:
       with:
         sonar-options: ${{inputs.sonar-options}}
     
